conditions:
- child: Qwen_framework
  parent: name
  type: EQ
  value: Qwen
- child: Qwen_llm
  parent: name
  type: EQ
  value: Qwen
- child: Qwen_max_tokens
  parent: name
  type: EQ
  value: Qwen
- child: Qwen_temperature
  parent: name
  type: EQ
  value: Qwen
- child: Qwen_uri
  parent: name
  type: EQ
  value: Qwen
- child: gpt3.5_batch
  parent: name
  type: EQ
  value: gpt3.5
- child: gpt3.5_framework
  parent: name
  type: EQ
  value: gpt3.5
- child: gpt3.5_llm
  parent: name
  type: EQ
  value: gpt3.5
- child: gpt3.5_max_token
  parent: name
  type: EQ
  value: gpt3.5
- child: gpt3.5_model
  parent: name
  type: EQ
  value: gpt3.5
- child: gpt3.5_temperature
  parent: name
  type: EQ
  value: gpt3.5
- child: gpt4_api_key
  parent: name
  type: EQ
  value: gpt4
- child: gpt4_batch
  parent: name
  type: EQ
  value: gpt4
- child: gpt4_framework
  parent: name
  type: EQ
  value: gpt4
- child: gpt4_llm
  parent: name
  type: EQ
  value: gpt4
- child: gpt4_max_tokens
  parent: name
  type: EQ
  value: gpt4
- child: gpt4_temperature
  parent: name
  type: EQ
  value: gpt4
- child: gpt4_truncate
  parent: name
  type: EQ
  value: gpt4
- child: mistralai_7b_huggingface_device_map
  parent: name
  type: EQ
  value: mistralai_7b
- child: mistralai_7b_huggingface_framework
  parent: name
  type: EQ
  value: mistralai_7b
- child: mistralai_7b_huggingface_llm
  parent: name
  type: EQ
  value: mistralai_7b
- child: mistralai_7b_huggingface_max_tokens
  parent: name
  type: EQ
  value: mistralai_7b
- child: mistralai_7b_huggingface_model
  parent: name
  type: EQ
  value: mistralai_7b
- child: mistralai_7b_huggingface_model_kwargs
  parent: name
  type: EQ
  value: mistralai_7b
- child: mistralai_7b_huggingface_temperature
  parent: name
  type: EQ
  value: mistralai_7b
- child: mistralai_7b_openailike_api_base
  parent: name
  type: EQ
  value: mistralai_7b
- child: mistralai_7b_openailike_api_key
  parent: name
  type: EQ
  value: mistralai_7b
- child: mistralai_7b_openailike_batch
  parent: name
  type: EQ
  value: mistralai_7b
- child: mistralai_7b_openailike_framework
  parent: name
  type: EQ
  value: mistralai_7b
- child: mistralai_7b_openailike_llm
  parent: name
  type: EQ
  value: mistralai_7b
- child: mistralai_7b_openailike_max_tokens
  parent: name
  type: EQ
  value: mistralai_7b
- child: mistralai_7b_openailike_model
  parent: name
  type: EQ
  value: mistralai_7b
- child: mistralai_7b_openailike_temperature
  parent: name
  type: EQ
  value: mistralai_7b
- child: mistralai_7b_vllm_framework
  parent: name
  type: EQ
  value: mistralai_7b
- child: mistralai_7b_vllm_llm
  parent: name
  type: EQ
  value: mistralai_7b
- child: mistralai_7b_vllm_max_tokens
  parent: name
  type: EQ
  value: mistralai_7b
- child: mistralai_7b_vllm_temperature
  parent: name
  type: EQ
  value: mistralai_7b
- child: mistralai_7b_vllm_top_p
  parent: name
  type: EQ
  value: mistralai_7b
forbiddens: []
format_version: 0.4
hyperparameters:
- choices:
  - gpt3.5
  - mistralai_7b
  - mistralai_7b_openailike
  - mistralai_7b_vllm
  - gpt4
  - Qwen
  default_value: gpt3.5
  meta: null
  name: name
  type: categorical
  weights:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
- choices:
  - vllm_api
  default_value: vllm_api
  meta: null
  name: Qwen_framework
  type: categorical
  weights: null
- choices:
  - Qwen/Qwen2.5-14B-Instruct-AWQ
  default_value: Qwen/Qwen2.5-14B-Instruct-AWQ
  meta: null
  name: Qwen_llm
  type: categorical
  weights: null
- choices:
  - 400
  default_value: 400
  meta: null
  name: Qwen_max_tokens
  type: categorical
  weights: null
- default_value: 1.0
  log: false
  lower: 0.0
  meta: null
  name: Qwen_temperature
  type: uniform_float
  upper: 2.0
- choices:
  - http://localhost:8012
  default_value: http://localhost:8012
  meta: null
  name: Qwen_uri
  type: categorical
  weights: null
- choices:
  - 16
  default_value: 16
  meta: null
  name: gpt3.5_batch
  type: categorical
  weights: null
- choices:
  - llama_index_llm
  default_value: llama_index_llm
  meta: null
  name: gpt3.5_framework
  type: categorical
  weights: null
- choices:
  - openai
  default_value: openai
  meta: null
  name: gpt3.5_llm
  type: categorical
  weights: null
- choices:
  - 512
  default_value: 512
  meta: null
  name: gpt3.5_max_token
  type: categorical
  weights: null
- choices:
  - gpt-3.5-turbo-16k
  default_value: gpt-3.5-turbo-16k
  meta: null
  name: gpt3.5_model
  type: categorical
  weights: null
- default_value: 1.0
  log: false
  lower: 0.0
  meta: null
  name: gpt3.5_temperature
  type: uniform_float
  upper: 2.0
- choices:
  - your_api_key
  default_value: your_api_key
  meta: null
  name: gpt4_api_key
  type: categorical
  weights: null
- choices:
  - 16
  default_value: 16
  meta: null
  name: gpt4_batch
  type: categorical
  weights: null
- choices:
  - openai_llm
  default_value: openai_llm
  meta: null
  name: gpt4_framework
  type: categorical
  weights: null
- choices:
  - gpt-4-turbo-2024-04-09
  default_value: gpt-4-turbo-2024-04-09
  meta: null
  name: gpt4_llm
  type: categorical
  weights: null
- choices:
  - 512
  default_value: 512
  meta: null
  name: gpt4_max_tokens
  type: categorical
  weights: null
- default_value: 1.0
  log: false
  lower: 0.0
  meta: null
  name: gpt4_temperature
  type: uniform_float
  upper: 2.0
- choices:
  - 4000
  default_value: 4000
  meta: null
  name: gpt4_truncate
  type: categorical
  weights: null
- choices:
  - auto
  default_value: auto
  meta: null
  name: mistralai_7b_huggingface_device_map
  type: categorical
  weights: null
- choices:
  - llama_index_llm
  default_value: llama_index_llm
  meta: null
  name: mistralai_7b_huggingface_framework
  type: categorical
  weights: null
- choices:
  - huggingface
  default_value: huggingface
  meta: null
  name: mistralai_7b_huggingface_llm
  type: categorical
  weights: null
- choices:
  - 512
  default_value: 512
  meta: null
  name: mistralai_7b_huggingface_max_tokens
  type: categorical
  weights: null
- choices:
  - mistralai/Mistral-7B-Instruct-v0.2
  default_value: mistralai/Mistral-7B-Instruct-v0.2
  meta: null
  name: mistralai_7b_huggingface_model
  type: categorical
  weights: null
- choices:
  - &id001
    torch_dtype: float16
  default_value: *id001
  meta: null
  name: mistralai_7b_huggingface_model_kwargs
  type: categorical
  weights: null
- default_value: 1.0
  log: false
  lower: 0.0
  meta: null
  name: mistralai_7b_huggingface_temperature
  type: uniform_float
  upper: 2.0
- choices:
  - your_api_base
  default_value: your_api_base
  meta: null
  name: mistralai_7b_openailike_api_base
  type: categorical
  weights: null
- choices:
  - your_api_key
  default_value: your_api_key
  meta: null
  name: mistralai_7b_openailike_api_key
  type: categorical
  weights: null
- choices:
  - 16
  default_value: 16
  meta: null
  name: mistralai_7b_openailike_batch
  type: categorical
  weights: null
- choices:
  - llama_index_llm
  default_value: llama_index_llm
  meta: null
  name: mistralai_7b_openailike_framework
  type: categorical
  weights: null
- choices:
  - openailike
  default_value: openailike
  meta: null
  name: mistralai_7b_openailike_llm
  type: categorical
  weights: null
- choices:
  - 512
  default_value: 512
  meta: null
  name: mistralai_7b_openailike_max_tokens
  type: categorical
  weights: null
- choices:
  - mistralai/Mistral-7B-Instruct-v0.2
  default_value: mistralai/Mistral-7B-Instruct-v0.2
  meta: null
  name: mistralai_7b_openailike_model
  type: categorical
  weights: null
- default_value: 1.0
  log: false
  lower: 0.0
  meta: null
  name: mistralai_7b_openailike_temperature
  type: uniform_float
  upper: 2.0
- choices:
  - vllm
  default_value: vllm
  meta: null
  name: mistralai_7b_vllm_framework
  type: categorical
  weights: null
- choices:
  - mistralai/Mistral-7B-Instruct-v0.2
  default_value: mistralai/Mistral-7B-Instruct-v0.2
  meta: null
  name: mistralai_7b_vllm_llm
  type: categorical
  weights: null
- choices:
  - 512
  default_value: 512
  meta: null
  name: mistralai_7b_vllm_max_tokens
  type: categorical
  weights: null
- default_value: 1.0
  log: false
  lower: 0.0
  meta: null
  name: mistralai_7b_vllm_temperature
  type: uniform_float
  upper: 2.0
- default_value: 0.5
  log: false
  lower: 0.0
  meta: null
  name: mistralai_7b_vllm_top_p
  type: uniform_float
  upper: 1.0
name: null
python_module_version: 1.2.0
