prompt_maker:
  method:
      - fstring
      - window_replacement
      - long_context_reorder
  prompt:
    set:
      - "Tell me something about the question: {query} \n\n {retrieved_contents}"
      - "Question: {query} \n Something to read: {retrieved_contents} \n What's your answer?"